// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package postgresServer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GeneratorProjectFeaturedRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneratorProjectFeaturedRequest) Reset()         { *m = GeneratorProjectFeaturedRequest{} }
func (m *GeneratorProjectFeaturedRequest) String() string { return proto.CompactTextString(m) }
func (*GeneratorProjectFeaturedRequest) ProtoMessage()    {}
func (*GeneratorProjectFeaturedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6d95b32c3e58f432, []int{0}
}
func (m *GeneratorProjectFeaturedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneratorProjectFeaturedRequest.Unmarshal(m, b)
}
func (m *GeneratorProjectFeaturedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneratorProjectFeaturedRequest.Marshal(b, m, deterministic)
}
func (dst *GeneratorProjectFeaturedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneratorProjectFeaturedRequest.Merge(dst, src)
}
func (m *GeneratorProjectFeaturedRequest) XXX_Size() int {
	return xxx_messageInfo_GeneratorProjectFeaturedRequest.Size(m)
}
func (m *GeneratorProjectFeaturedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneratorProjectFeaturedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GeneratorProjectFeaturedRequest proto.InternalMessageInfo

type GeneratorProjectsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneratorProjectsRequest) Reset()         { *m = GeneratorProjectsRequest{} }
func (m *GeneratorProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*GeneratorProjectsRequest) ProtoMessage()    {}
func (*GeneratorProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6d95b32c3e58f432, []int{1}
}
func (m *GeneratorProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneratorProjectsRequest.Unmarshal(m, b)
}
func (m *GeneratorProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneratorProjectsRequest.Marshal(b, m, deterministic)
}
func (dst *GeneratorProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneratorProjectsRequest.Merge(dst, src)
}
func (m *GeneratorProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_GeneratorProjectsRequest.Size(m)
}
func (m *GeneratorProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneratorProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GeneratorProjectsRequest proto.InternalMessageInfo

type ProjectFeature struct {
	ProjectFeaturesId          int32    `protobuf:"varint,1,opt,name=project_features_id,json=projectFeaturesId,proto3" json:"project_features_id,omitempty"`
	ProjectFeaturesType        string   `protobuf:"bytes,2,opt,name=project_features_type,json=projectFeaturesType,proto3" json:"project_features_type,omitempty"`
	ProjectFeaturesInheritFrom int32    `protobuf:"varint,3,opt,name=project_features_inherit_from,json=projectFeaturesInheritFrom,proto3" json:"project_features_inherit_from,omitempty"`
	ProjectFeaturesConfig      string   `protobuf:"bytes,4,opt,name=project_features_config,json=projectFeaturesConfig,proto3" json:"project_features_config,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *ProjectFeature) Reset()         { *m = ProjectFeature{} }
func (m *ProjectFeature) String() string { return proto.CompactTextString(m) }
func (*ProjectFeature) ProtoMessage()    {}
func (*ProjectFeature) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6d95b32c3e58f432, []int{2}
}
func (m *ProjectFeature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectFeature.Unmarshal(m, b)
}
func (m *ProjectFeature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectFeature.Marshal(b, m, deterministic)
}
func (dst *ProjectFeature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectFeature.Merge(dst, src)
}
func (m *ProjectFeature) XXX_Size() int {
	return xxx_messageInfo_ProjectFeature.Size(m)
}
func (m *ProjectFeature) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectFeature.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectFeature proto.InternalMessageInfo

func (m *ProjectFeature) GetProjectFeaturesId() int32 {
	if m != nil {
		return m.ProjectFeaturesId
	}
	return 0
}

func (m *ProjectFeature) GetProjectFeaturesType() string {
	if m != nil {
		return m.ProjectFeaturesType
	}
	return ""
}

func (m *ProjectFeature) GetProjectFeaturesInheritFrom() int32 {
	if m != nil {
		return m.ProjectFeaturesInheritFrom
	}
	return 0
}

func (m *ProjectFeature) GetProjectFeaturesConfig() string {
	if m != nil {
		return m.ProjectFeaturesConfig
	}
	return ""
}

type ProjectFeaturedDetails struct {
	ProjectId            int32             `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName          string            `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ProjectContent       string            `protobuf:"bytes,3,opt,name=project_content,json=projectContent,proto3" json:"project_content,omitempty"`
	ProjectFeatures      []*ProjectFeature `protobuf:"bytes,4,rep,name=project_features,json=projectFeatures,proto3" json:"project_features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProjectFeaturedDetails) Reset()         { *m = ProjectFeaturedDetails{} }
func (m *ProjectFeaturedDetails) String() string { return proto.CompactTextString(m) }
func (*ProjectFeaturedDetails) ProtoMessage()    {}
func (*ProjectFeaturedDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6d95b32c3e58f432, []int{3}
}
func (m *ProjectFeaturedDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectFeaturedDetails.Unmarshal(m, b)
}
func (m *ProjectFeaturedDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectFeaturedDetails.Marshal(b, m, deterministic)
}
func (dst *ProjectFeaturedDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectFeaturedDetails.Merge(dst, src)
}
func (m *ProjectFeaturedDetails) XXX_Size() int {
	return xxx_messageInfo_ProjectFeaturedDetails.Size(m)
}
func (m *ProjectFeaturedDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectFeaturedDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectFeaturedDetails proto.InternalMessageInfo

func (m *ProjectFeaturedDetails) GetProjectId() int32 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *ProjectFeaturedDetails) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *ProjectFeaturedDetails) GetProjectContent() string {
	if m != nil {
		return m.ProjectContent
	}
	return ""
}

func (m *ProjectFeaturedDetails) GetProjectFeatures() []*ProjectFeature {
	if m != nil {
		return m.ProjectFeatures
	}
	return nil
}

type ProjectDetails struct {
	ProjectId            int32    `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName          string   `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ProjectContent       string   `protobuf:"bytes,3,opt,name=project_content,json=projectContent,proto3" json:"project_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectDetails) Reset()         { *m = ProjectDetails{} }
func (m *ProjectDetails) String() string { return proto.CompactTextString(m) }
func (*ProjectDetails) ProtoMessage()    {}
func (*ProjectDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6d95b32c3e58f432, []int{4}
}
func (m *ProjectDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectDetails.Unmarshal(m, b)
}
func (m *ProjectDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectDetails.Marshal(b, m, deterministic)
}
func (dst *ProjectDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectDetails.Merge(dst, src)
}
func (m *ProjectDetails) XXX_Size() int {
	return xxx_messageInfo_ProjectDetails.Size(m)
}
func (m *ProjectDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectDetails proto.InternalMessageInfo

func (m *ProjectDetails) GetProjectId() int32 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *ProjectDetails) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *ProjectDetails) GetProjectContent() string {
	if m != nil {
		return m.ProjectContent
	}
	return ""
}

type GeneratorProjectsReply struct {
	Projects             []*ProjectDetails `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GeneratorProjectsReply) Reset()         { *m = GeneratorProjectsReply{} }
func (m *GeneratorProjectsReply) String() string { return proto.CompactTextString(m) }
func (*GeneratorProjectsReply) ProtoMessage()    {}
func (*GeneratorProjectsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6d95b32c3e58f432, []int{5}
}
func (m *GeneratorProjectsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneratorProjectsReply.Unmarshal(m, b)
}
func (m *GeneratorProjectsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneratorProjectsReply.Marshal(b, m, deterministic)
}
func (dst *GeneratorProjectsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneratorProjectsReply.Merge(dst, src)
}
func (m *GeneratorProjectsReply) XXX_Size() int {
	return xxx_messageInfo_GeneratorProjectsReply.Size(m)
}
func (m *GeneratorProjectsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneratorProjectsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GeneratorProjectsReply proto.InternalMessageInfo

func (m *GeneratorProjectsReply) GetProjects() []*ProjectDetails {
	if m != nil {
		return m.Projects
	}
	return nil
}

type GeneratorProjectFeaturedReply struct {
	Projects             []*ProjectFeaturedDetails `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GeneratorProjectFeaturedReply) Reset()         { *m = GeneratorProjectFeaturedReply{} }
func (m *GeneratorProjectFeaturedReply) String() string { return proto.CompactTextString(m) }
func (*GeneratorProjectFeaturedReply) ProtoMessage()    {}
func (*GeneratorProjectFeaturedReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6d95b32c3e58f432, []int{6}
}
func (m *GeneratorProjectFeaturedReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneratorProjectFeaturedReply.Unmarshal(m, b)
}
func (m *GeneratorProjectFeaturedReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneratorProjectFeaturedReply.Marshal(b, m, deterministic)
}
func (dst *GeneratorProjectFeaturedReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneratorProjectFeaturedReply.Merge(dst, src)
}
func (m *GeneratorProjectFeaturedReply) XXX_Size() int {
	return xxx_messageInfo_GeneratorProjectFeaturedReply.Size(m)
}
func (m *GeneratorProjectFeaturedReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneratorProjectFeaturedReply.DiscardUnknown(m)
}

var xxx_messageInfo_GeneratorProjectFeaturedReply proto.InternalMessageInfo

func (m *GeneratorProjectFeaturedReply) GetProjects() []*ProjectFeaturedDetails {
	if m != nil {
		return m.Projects
	}
	return nil
}

func init() {
	proto.RegisterType((*GeneratorProjectFeaturedRequest)(nil), "postgresServer.GeneratorProjectFeaturedRequest")
	proto.RegisterType((*GeneratorProjectsRequest)(nil), "postgresServer.GeneratorProjectsRequest")
	proto.RegisterType((*ProjectFeature)(nil), "postgresServer.ProjectFeature")
	proto.RegisterType((*ProjectFeaturedDetails)(nil), "postgresServer.ProjectFeaturedDetails")
	proto.RegisterType((*ProjectDetails)(nil), "postgresServer.ProjectDetails")
	proto.RegisterType((*GeneratorProjectsReply)(nil), "postgresServer.GeneratorProjectsReply")
	proto.RegisterType((*GeneratorProjectFeaturedReply)(nil), "postgresServer.GeneratorProjectFeaturedReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	GeneratorProjects(ctx context.Context, in *GeneratorProjectsRequest, opts ...grpc.CallOption) (*GeneratorProjectsReply, error)
	GeneratorProjectFeatured(ctx context.Context, in *GeneratorProjectFeaturedRequest, opts ...grpc.CallOption) (*GeneratorProjectFeaturedReply, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) GeneratorProjects(ctx context.Context, in *GeneratorProjectsRequest, opts ...grpc.CallOption) (*GeneratorProjectsReply, error) {
	out := new(GeneratorProjectsReply)
	err := c.cc.Invoke(ctx, "/postgresServer.Api/GeneratorProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GeneratorProjectFeatured(ctx context.Context, in *GeneratorProjectFeaturedRequest, opts ...grpc.CallOption) (*GeneratorProjectFeaturedReply, error) {
	out := new(GeneratorProjectFeaturedReply)
	err := c.cc.Invoke(ctx, "/postgresServer.Api/GeneratorProjectFeatured", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	GeneratorProjects(context.Context, *GeneratorProjectsRequest) (*GeneratorProjectsReply, error)
	GeneratorProjectFeatured(context.Context, *GeneratorProjectFeaturedRequest) (*GeneratorProjectFeaturedReply, error)
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_GeneratorProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratorProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GeneratorProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postgresServer.Api/GeneratorProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GeneratorProjects(ctx, req.(*GeneratorProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GeneratorProjectFeatured_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratorProjectFeaturedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GeneratorProjectFeatured(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postgresServer.Api/GeneratorProjectFeatured",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GeneratorProjectFeatured(ctx, req.(*GeneratorProjectFeaturedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "postgresServer.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratorProjects",
			Handler:    _Api_GeneratorProjects_Handler,
		},
		{
			MethodName: "GeneratorProjectFeatured",
			Handler:    _Api_GeneratorProjectFeatured_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_6d95b32c3e58f432) }

var fileDescriptor_api_6d95b32c3e58f432 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0x95, 0x0b, 0xad, 0xea, 0xa1, 0x82, 0xb2, 0x08, 0x6a, 0x59, 0xa2, 0x05, 0x1f, 0xa8, 0x2f,
	0x75, 0x25, 0x2a, 0xf5, 0xd0, 0x1b, 0xa5, 0xa2, 0xe2, 0x12, 0x45, 0x0e, 0x77, 0xe4, 0xd8, 0x03,
	0x71, 0x84, 0xbd, 0x9b, 0xdd, 0x25, 0x92, 0x93, 0xff, 0x98, 0xdf, 0x91, 0x5b, 0xfe, 0x42, 0x84,
	0x3f, 0x90, 0xbc, 0x0e, 0x84, 0x53, 0xae, 0x6f, 0xde, 0xbc, 0x79, 0x6f, 0x77, 0x67, 0x41, 0xf7,
	0x58, 0xe8, 0x30, 0x4e, 0x25, 0x25, 0x4d, 0x46, 0x85, 0x5c, 0x73, 0x14, 0x17, 0xc8, 0x6f, 0x91,
	0x5b, 0x43, 0xf8, 0xf6, 0x1f, 0x63, 0xe4, 0x9e, 0xa4, 0xfc, 0x9c, 0xd3, 0x6b, 0xf4, 0xe5, 0x0c,
	0x3d, 0xb9, 0xe5, 0x18, 0xb8, 0x78, 0xb3, 0x45, 0x21, 0x2d, 0x13, 0x0c, 0x95, 0x22, 0x8a, 0xda,
	0x93, 0x06, 0xcd, 0x72, 0x1b, 0x71, 0xa0, 0xc3, 0x32, 0x64, 0xb9, 0xca, 0x20, 0xb1, 0x0c, 0x03,
	0x43, 0x1b, 0x68, 0xf6, 0x7b, 0xb7, 0xcd, 0x4a, 0x64, 0x31, 0x0f, 0xc8, 0x18, 0xba, 0x15, 0xbe,
	0x4c, 0x18, 0x1a, 0xef, 0x06, 0x9a, 0xad, 0xbb, 0x1d, 0xa5, 0x63, 0x91, 0x30, 0x24, 0x13, 0xe8,
	0x57, 0x67, 0xc4, 0x57, 0xc8, 0x43, 0xb9, 0x5c, 0x71, 0x1a, 0x19, 0xb5, 0x74, 0x9a, 0xa9, 0x4e,
	0xcb, 0x28, 0x33, 0x4e, 0x23, 0xf2, 0x1b, 0xbe, 0x54, 0x24, 0x7c, 0x1a, 0xaf, 0xc2, 0xb5, 0x51,
	0x4f, 0x07, 0x77, 0x95, 0xe6, 0x69, 0x5a, 0xb4, 0x1e, 0x34, 0xe8, 0x29, 0x07, 0xf5, 0x0f, 0xa5,
	0x17, 0x6e, 0x04, 0xe9, 0x03, 0x14, 0x92, 0xfb, 0xc0, 0x7a, 0x8e, 0xcc, 0x03, 0x32, 0x84, 0x4f,
	0x45, 0x39, 0xf6, 0xa2, 0x22, 0x5f, 0x23, 0xc7, 0xce, 0xbc, 0x08, 0xc9, 0x77, 0x68, 0x15, 0x14,
	0x9f, 0xc6, 0x12, 0x63, 0x99, 0x26, 0xd1, 0xdd, 0x66, 0x0e, 0x4f, 0x33, 0x94, 0xcc, 0xe1, 0xb3,
	0xea, 0xde, 0xa8, 0x0f, 0x6a, 0x76, 0x63, 0xfc, 0xd5, 0x29, 0xdf, 0xb0, 0x53, 0x36, 0xeb, 0xb6,
	0x94, 0x58, 0xd6, 0xfd, 0xfe, 0x06, 0xdf, 0x3e, 0x87, 0xb5, 0x80, 0xde, 0x0b, 0x6f, 0x8b, 0x6d,
	0x12, 0xf2, 0x07, 0x3e, 0xe6, 0x5c, 0x61, 0x68, 0x47, 0x93, 0xe5, 0xb6, 0xdd, 0x3d, 0xdf, 0xf2,
	0xa1, 0x7f, 0xf8, 0x51, 0xef, 0xc4, 0xff, 0x56, 0xc4, 0x47, 0xc7, 0x8f, 0x2d, 0xa8, 0x0c, 0x19,
	0x3f, 0x6a, 0x50, 0x9b, 0xb0, 0x90, 0x20, 0xb4, 0x2b, 0x11, 0x88, 0xad, 0xca, 0x1d, 0xda, 0x20,
	0x73, 0x74, 0x02, 0x73, 0x67, 0xf9, 0xae, 0xba, 0x85, 0x85, 0x37, 0xf2, 0xf3, 0x35, 0x0d, 0x65,
	0xa5, 0xcd, 0x1f, 0xa7, 0x37, 0xb0, 0x4d, 0x72, 0xf9, 0x21, 0xfd, 0x3b, 0x7e, 0x3d, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x84, 0x24, 0xe8, 0xe0, 0x48, 0x04, 0x00, 0x00,
}
